### PR TITLE
Fix line numbers menu: use g_settings_bind correctly

### PR DESCRIPTION
**Pull request by mbkma**
Test: right-click on line-numbers

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
This fixes a mistake that reversed the order of two variables. With master as of now, if you right click just inside the LEFT EDGE of the view w line numbers enabled, pluma crashes. This can cause loss of work. With this change, that same right-click gets a menuitem to enable or disable line numbers. This works and is a needed bugfix. 

Indents looks the same too, this looks ready to go.

**Comment by raveit65** [comment]
@mbkma 

> Test: right-click on line-numbers

What should happen?
Here behaviour is same as before. No context menu or what ever you expect.
Beside from that pluma builds and runs fine.

**Comment by mbkma** [comment]
@raveit65 before it crashes / after it displays the context menu.

Screenshot at 2020-11-22 13-49-12

**Review by rbuj — APPROVED** [review]
Yhe setting's key and the object's property are swapped on g_settings_bind, so there is a segmentation fault.

**Comment by raveit65** [comment]
I get no crash or the context menu w/wo the commit. Maybe HIDPI related?
Any way, fix is fine. I will cherry-pick it to stable.

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by mbkma** [comment]
@raveit65  I don't think this issue exists in 1.24.

**Comment by raveit65** [comment]
Ok, good. 
Cherry-picking doesn't clean apply.

**Comment by raveit65** [comment]
Good news, travis CI builds starting immediately again :) 
https://travis-ci.org/github/mate-desktop/pluma/builds/745209847

**Comment by rbuj** [comment]
culprit 2edb465b646f671f3372c70f020bd3d3076e86ad

**Pull request merged**
