### PR TITLE
quickopen plugin: change code for Python 2 & 3 compatibility.

### PR DESCRIPTION
**Pull request by monnerat**
This rewrites the plugin in Python 3, while retaining Python 2 compatibility.

In addition, some bugs are fixed and the Gtk-3 compatibility is improved (mainly regarding widget deprecation).

### CODE REVIEW

**Comment by raveit65** [comment]
@monnerat 
How can i test this in fedora without libpeas (python2) ?

**Comment by monnerat** [comment]
> How can i test this in fedora without libpeas (python2) ?

I used Fedora 27 for tests. I don't think it is possible to do it on Fedora 29 now that gnome people have removed most Python 2 support. The easiest seems to create a VM for that.

**Comment by raveit65** [comment]
This something i want to avoid :)
I am looking forward and I'd like to test it directly for f30 with python3.
Maybe you can prepare the missing 5th PR for porting main pluma to python3?
Or can i use some commits from previous PR?

**Comment by monnerat** [comment]
> Maybe you can prepare the missing 5th PR for porting main pluma to python3?
I did not submit a PR for it since it should be applied after the 4 others. However you can find the commit at https://github.com/monnerat/pluma/commit/e5b55e46fc260b20a7496f94d555872f63c8a9ae.

**Comment by raveit65** [comment]
@monnerat 
I just released pluma-1.23.0 for better testing.
Can please rebase PRs against master?

**Comment by monnerat** [comment]
> Can please rebase PRs against master?

Done.

**Comment by raveit65** [comment]
Scratch builds of actual libpeas with libpeas-loader-python (python2) for better testing with f29/30.
https://koji.fedoraproject.org/koji/taskinfo?taskID=35257764
https://koji.fedoraproject.org/koji/taskinfo?taskID=35257779
@monnerat @vkareh @rbuj  ^^^

**Comment by vkareh** [comment]
This works fine with Python2 - not sure how to test with Python3. I changed the plugin loader manually to python3, but I keep getting an error from libpeas:
```
(pluma:2180): libpeas-WARNING **: 10:34:58.457: The 'python3' plugin loader has not been enabled
```
But it seems to be there somewhere:
```
$ locate libpeas | grep python3
/usr/lib/x86_64-linux-gnu/libpeas-1.0/loaders/libpython3loader.so
```
This is on Ubuntu MATE 19.04...
Any ideas?

**Comment by monnerat** [comment]
> This works fine with Python2 - not sure how to test with Python3.

Apply commit https://github.com/monnerat/pluma/commit/e5b55e46fc260b20a7496f94d555872f63c8a9ae (6 changes in 6 files) and recompile Pluma.
I did not issue a PR for it until now since it works only if the PRs for the 4 Python plugins are applied first.

**Comment by raveit65** [comment]
@vkareh 
In fedora with my libeas scratch build it looks like this.
```
[root@mother rave]# rpm -qa libpeas*
libpeas-devel-1.22.0-11.fc30.x86_64
libpeas-loader-python3-1.22.0-11.fc30.x86_64
libpeas-1.22.0-11.fc30.x86_64
libpeas-loader-python-1.22.0-11.fc30.x86_64
libpeas-gtk-1.22.0-11.fc30.x86_64
```

**Comment by raveit65** [comment]
Ok, building the plugin with python2 and running pluma in general works. 
But how the plugin works after it is enabled in settings?
:)

**Comment by raveit65** [comment]
Ok, found the menu-entry. Works fine with python2. Same with using crtl+alt+o with keyboard.
Now i start building and testing with python3.

**Comment by vkareh** [comment]
Okay, retested by enabling python3 based on @monnerat's `switch_to_python3` branch. It works very well :)

**Comment by raveit65** [comment]
Lets go to next modul.....

**Comment by monnerat** [comment]
Thanks for merging :-)

**Pull request merged**
