### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by mbkma**
With more up to date information and markdown style.

### CODE REVIEW

**Comment by raveit65** [comment]
Build error.
```
Makefile.am: error: required file './README' not found
```
https://travis-ci.org/github/mate-desktop/pluma/jobs/731885978#L822

**Comment by mbkma** [comment]
@raveit65 thanks, should be fixed now.

**Review by lukefromdc — APPROVED** [review]
Very nice update, and I checked configuration and build: no unpleasant surprises there

**Review by raveit65 — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
@mbkma 
Btw., you can work now directly in this repo as pluma maintainer. eg. creating branches for a PR.

**Comment by mbkma** [comment]
@raveit65 ok, good to know :)

**Pull request merged**
