### PR TITLE
pluma-spell-setup-dialog.ui plugin: avoid GtkRadioButton:xalign

### PR DESCRIPTION
**Pull request by sc0w**
spell_setup

### CODE REVIEW

**Comment by raveit65** [comment]
Feel free to use and rebase last commit. It fixes a deprecation for the label and  now it looks better in glade.....

**Comment by lukefromdc** [comment]
Rebased and merged with
https://github.com/mate-desktop/pluma/commit/f248f85f74f4d6bc58e6244cc43f91f8ccb15ede
and
https://github.com/mate-desktop/pluma/commit/3858a43e197468abf210df7243488737e2877539

**Comment by sc0w** [comment]
@raveit65 

> It fixes a deprecation for the label

seems GtkLabel:xalign is not deprecated

https://developer.gnome.org/gtk4/unstable/GtkLabel.html#GtkLabel--xalign

**Comment by raveit65** [comment]
But i had a warning in glade-3.20.0-3.fc26.x86_64 with using 
```
<property name="xalign">0</property>
```

**Comment by sc0w** [comment]
weird, not here with glade 3.20.2-1 (debian/testing)

**Comment by raveit65** [comment]
Confirmed, with glade-3.20.2 or latest 3.20.4 the warnings are gone.
But i don't think we need to revert it.
property name="halign">start</property  does the same.
I will use 3.20.4 for further reviews.
Btw. can fix all deprecations in one PR for a Ui file, for reducing reviewer work?
Or better put all ui files with several commits in one PR for an application.
It's easier to test all Ui files in one rush.

**Pull request closed without merging**
