### PR TITLE
deprecations

### PR DESCRIPTION
**Pull request by raveit65**
please review

### CODE REVIEW

**Comment by lukefromdc** [comment]
All the UI elements are rendering normally, I don't see any issues that came from this PR and have been using it a couple weeks.

I've had occasional issues most of the summer with Pluma going nonresponsive but I'm pretty sure that predates this PR. That issue is too infrequent to invoke at will for debugging, happens just often enough to be a nuisance when writing software, actlng like Gedit used to when the file browser from which a file had been opened was killed.

**Comment by monsta** [comment]
GTK+2 build is ok (well, it's not really affected by these changes).

**Comment by monsta** [comment]
All good in GTK+3 with 3.20 as well.

**Comment by raveit65** [comment]
merged.

**Pull request closed without merging**
