### PR TITLE
Don't add and trim trailing newlines from documents

### PR DESCRIPTION
**Pull request by ntninja**
Fixes issue #124.

### CODE REVIEW

**Comment by lukefromdc** [comment]
How do I test this?

**Comment by alexander255** [comment]
Good point! :slightly_smiling_face: 

Here's a testing scenario:

1. Start `pluma` without this patch applied
2. Open/create a text file, write a single line of text with no line breaks and save the document
3. Close `pluma`
4. Open the text file in a hex editor (such as `ghex`)
5. Observe that additionally to the content you wrote a newline character (0x10) was appended to the contents
6. Close the hex editor again
7. Open the same text file in patched `pluma` with these changes applied
8. Observe that the final newline is now visible
9. Remove the final newline and save again
10. Close `pluma` again
11. Open the text file in the hex editor again
12. Observe that now only the content was written without any extra characters

**Comment by lukefromdc** [comment]
With pluma from master I saved this file (with no newline in it) 
`1234566789010`
and got this hexdump from it:

```
0000000 3231 3433 3635 3736 3938 3130 0a30     
000000e

```

**Comment by alexander255** [comment]
The output is correct, but you apparently set the Hex editor to 16-bit little endian :slightly_smiling_face: 
See how it groups each set of two characters (16-bit) and reverses their order (little endian)? Try setting it to 8-bit and it should be more obvious what is happening!

**Comment by alexander255** [comment]
Also it appears I wrote some nonsense into my scenario: The newline character is of course `0x0A` (=10d), not 0x10 (= 16d). Sorry bout that!

**Comment by lukefromdc** [comment]
Also note that for testing your test files need to be created with the version of pluma being tested

**Comment by alexander255** [comment]
@lukefromdc: Thanks for trying to review this!

A note regarding your last comment: You can also create the testing files without switching pluma version (`printf 'bla\n' > test-file` vs `printf 'bla' > test-file`), but then you cannot test the whole load+edit+save cycle making it rather useless.

**Comment by lukefromdc** [comment]
@monsta @raveit65 , are either of you able to properly evaluate this?

**Comment by raveit65** [comment]
Ok that works, with PR the newline is visible in pluma and can be removed.
But why this is a problem?
And maybe we can follow gedit upstream and remove the whole file, as all is now GtkSourceView?
See https://gitlab.gnome.org/GNOME/gedit/commit/f7607b420e52836b5c177d3835185bcf562fb7ac
@monsta @sc0w 
Thoughts?

**Comment by sc0w** [comment]
I noticed vi / vim works like pluma without this PR, and it shows a warning opening files without new line at the end:



why?

we need a gsettings key to enable the new behavior of this PR?

**Comment by sc0w** [comment]
and github shows warning adding new files with no new line at the end:

**Comment by raveit65** [comment]
> and github shows warning adding new files with no new line at the end:

This isn't good

**Comment by sc0w** [comment]
I agree with the PR if it adds a gsettings key

gedit has this key:

**Comment by sc0w** [comment]
it was added in gedit with the commits:

https://gitlab.gnome.org/GNOME/gedit/commit/fe62ab8175747298a5315aaeed53ef0c56e60817

https://gitlab.gnome.org/GNOME/gedit/commit/42a8884a2b9b58bf5216c608f8266fde2af280b6

**Comment by sc0w** [comment]
`git diff` also shows warning with no new line at the end:

**Comment by raveit65** [comment]
Any news or progress?
Or should we close PR?

**Comment by raveit65** [comment]
Closing, ask for reopening if you want to work again on it.

**Pull request closed without merging**
