### PR TITLE
Add a new Configure dialog for the Spell Check plugin.

### PR DESCRIPTION
**Pull request by sleeveroller**
mate-desktop/pluma#90

There are three options for autocheck when a doc is loaded:

Always autocheck, Never autocheck and Remember the autocheck setting for each document

The chosen option is stored in the gsettings schema.
The default setting is to remember by document as this is what Pluma did previously.

### CODE REVIEW

**Comment by IndichRMV** [comment]
Thanks, sleeveroller! :-)

**Comment by infirit** [comment]
The gsettings schema Makefile changes are not looking ok, have a look at https://github.com/mate-desktop/mate-panel/blob/master/data/Makefile.am#L15 for an example. Also in.in indicates you want the strings in the gschema to be translated, but then you do not mark them with underscores, see https://github.com/mate-desktop/mate-panel/blob/master/data/org.mate.panel.gschema.xml.in.in for an example. Also [POTFILES.in](https://github.com/mate-desktop/mate-panel/blob/master/po/POTFILES.in) and [POTFILES.skip](https://github.com/mate-desktop/mate-panel/blob/master/po/POTFILES.skip) need to be updated with the new schema file.

There are whitespace changes from tabs to spaces (starting from set_language_from_metadata), can you please use tabs :smile:. While doing that please also fix the indentation of function arguments ([example](https://github.com/mate-desktop/pluma/pull/125/files#diff-7a018909bffbec89e859f6c5ab67f93eR1273)).

Last one, the help button does nothing. Probably because you use the ``dialog`` instead of ``widget`` in ``pluma_help_display``.

Other than that it work nicely.

**Comment by sleeveroller** [comment]
@infirit thanks for the feedback. I've been fixing up this commit.

I just have a few questions:

1. I've changed the help button to widget so now it launches the help file. But with a 'Page Not Found' error. Do I need to create a section in the Help file for this? Or should I remove the Help button completely? Or does someone else maintain the help file?

2. I've changed all the padded spaces to tabs (I'm using size 8 for the tabs). But in some cases things don't line up exactly. Should I add a couple some extra spaces after the tabs to get them to line up or should it just be enough tab characters to get it as close as possible to the line above.

3. I was planning to just do a new pull request with a single commit once this patch is finalized rebased off the latest master branch. But would it be better to do the tidy up as a change to the first pull request?

**Comment by infirit** [comment]
Thanks, here we go,

Regarding one, the way to show the spell checker help page with yelp is ``yelp "help:pluma/pluma-spell-checker-plugin"`` so we need to change ``pluma-spell-configure`` to ``pluma-spell-checker-plugin``

On two, I personally do not like tabs as we all have different tab settings, but pluma already had tabs so we have to :cry:. But yes, the common way it to use tabs and trailing spaces to line things up.

On three, yes please rebase and squash this into a single commit :smile:. Then just force push it to the same branch and all is ok.

And I changed the way how intltool extracts strings from gsettings schema's. I'll post a patch inline against your branch a bit later.

**Comment by infirit** [comment]
Here it is :smile: 
````diff
From 4e4ddcb8cd573c3048b5d71636a46e98ac895baf Mon Sep 17 00:00:00 2001
From: infirit <infirit@gmail.com>
Date: Thu, 17 Sep 2015 16:40:17 +0200
Subject: [PATCH] fixup spell check gschema

---
 configure.ac                                               |  1 +
 plugins/spell/Makefile.am                                  | 11 ++++-------
 plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in  | 14 ++++++++++++++
 .../spell/org.mate.pluma.plugins.spell.gschema.xml.in.in   | 14 --------------
 4 files changed, 19 insertions(+), 21 deletions(-)
 create mode 100644 plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in
 delete mode 100644 plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in.in

diff --git a/configure.ac b/configure.ac
index 641389a..faf12a9 100644
--- a/configure.ac
+++ b/configure.ac
@@ -405,6 +405,7 @@ plugins/snippets/Makefile
 plugins/snippets/snippets/Makefile
 plugins/sort/Makefile
 plugins/spell/Makefile
+plugins/spell/org.mate.pluma.plugins.spell.gschema.xml
 plugins/taglist/Makefile
 plugins/time/Makefile
 plugins/time/org.mate.pluma.plugins.time.gschema.xml
diff --git a/plugins/spell/Makefile.am b/plugins/spell/Makefile.am
index 185120b..d822700 100755
--- a/plugins/spell/Makefile.am
+++ b/plugins/spell/Makefile.am
@@ -51,20 +51,17 @@ plugin_in_files = spell.pluma-plugin.desktop.in
 plugin_DATA = $(plugin_in_files:.pluma-plugin.desktop.in=.pluma-plugin)
 
 @INTLTOOL_XML_NOMERGE_RULE@
-gsettings_SCHEMAS = org.mate.pluma.plugins.spell.gschema.xml
+spell_gschema_in = org.mate.pluma.plugins.spell.gschema.xml.in
+gsettings_SCHEMAs = $(spell_gschema_in:.xml.in=.xml)
 @GSETTINGS_RULES@
  
-%.gschema.xml.in: %.gschema.xml.in.in Makefile
-	$(AM_V_GEN) $(SED) -e 's^\@GETTEXT_PACKAGE\@^$(GETTEXT_PACKAGE)^g' < $< > $@
-
-
 EXTRA_DIST = 					\
 	$(ui_DATA)				\
 	$(plugin_in_files)			\
 	pluma-spell-marshal.list    	        \
-    	$(gsettings_SCHEMAS).in.in 
+	$(spell_gschema_in)
 
-CLEANFILES = $(BUILT_SOURCES) $(plugin_DATA) $(gsettings_SCHEMAS_in) $(gsettings_SCHEMASn)
+CLEANFILES = $(BUILT_SOURCES) $(plugin_DATA) $(gsettings_SCHEMAS)
 
 dist-hook:
 	cd $(distdir); rm -f $(BUILT_SOURCES)
diff --git a/plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in b/plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in
new file mode 100644
index 0000000..d78d58f
--- /dev/null
+++ b/plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in
@@ -0,0 +1,14 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<schemalist gettext-domain="@GETTEXT_PACKAGE@">
+  <enum id="org.mate.pluma.plugins.spell.AutocheckType">
+    <value value="0" nick="never"/>
+    <value value="1" nick="document"/>
+    <value value="2" nick="always"/>
+  </enum>
+  <schema path="/org/mate/pluma/plugins/spell/" id="org.mate.pluma.plugins.spell">
+    <key name="autocheck-type" enum="org.mate.pluma.plugins.spell.AutocheckType">
+      <default>'document'</default>
+      <summary>Autocheck Type</summary>
+    </key>
+  </schema>
+</schemalist>
diff --git a/plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in.in b/plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in.in
deleted file mode 100644
index d78d58f..0000000
--- a/plugins/spell/org.mate.pluma.plugins.spell.gschema.xml.in.in
+++ /dev/null
@@ -1,14 +0,0 @@
-<?xml version="1.0" encoding="UTF-8"?>
-<schemalist gettext-domain="@GETTEXT_PACKAGE@">
-  <enum id="org.mate.pluma.plugins.spell.AutocheckType">
-    <value value="0" nick="never"/>
-    <value value="1" nick="document"/>
-    <value value="2" nick="always"/>
-  </enum>
-  <schema path="/org/mate/pluma/plugins/spell/" id="org.mate.pluma.plugins.spell">
-    <key name="autocheck-type" enum="org.mate.pluma.plugins.spell.AutocheckType">
-      <default>'document'</default>
-      <summary>Autocheck Type</summary>
-    </key>
-  </schema>
-</schemalist>
-- 
2.5.2
````

**Comment by sleeveroller** [comment]
OK I've redone this commit and recreated the issue90 branch within my cloned repo.
Thanks very much for you help @infirit let me know if there are still issues with it.

**Pull request closed without merging**
