### PR TITLE
Migrate from intltool to gettext

### PR DESCRIPTION
**Pull request by yetist**
This PR is not finished, please don't merge it.

I am having trouble and need some help. I don't know how to write a correct `.its` file for some xml files. These files in `plugins/taglist` direcoty, named `*.tags.xml.in`, for example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<TagList xmlns="http://pluma.sourceforge.net/some-location">
<TagGroup name="XHTML 1.0 - Tags" sort="true">

  <Tag name="Abbreviated form">
    <Begin>&lt;abbr title="</Begin>
    <End>"&gt;&lt;/abbr&gt;</End>
  </Tag>
...
```
I don't know how to make `name` properties in `Tag` translatable, the string is `Abbreviated form`.

@mate-desktop/core-team @mate-desktop/contributors 
Who can help? Or do we need to modify the code to change the xml file structure?

BTW, {it,ru,uk}.po has errors, I temporarily disable them.

### CODE REVIEW

**Comment by sc0w** [comment]
I fixed `it` language at transifex

@monsta `ru` and `uk` have the same problems mentioned in https://github.com/mate-desktop/eom/pull/245

- affected lines in `ru`:

```
#: ../pluma/pluma-statusbar.c:352
#, c-format
msgid "There is a tab with errors"
msgid_plural "There are %d tabs with errors"
msgstr[0] "Есть вкладка с ошибками"
msgstr[1] "%d вкладок с ошибками"
msgstr[2] "%d вкладок с ошибками"
msgstr[3] "%d вкладок с ошибками"
```

- affected lines in `uk`:

```
#: ../pluma/pluma-commands-file.c:1165
#, c-format
msgid ""
"Changes made to the document in the last %ld minute will be permanently "
"lost."
msgid_plural ""
"Changes made to the document in the last %ld minutes will be permanently "
"lost."
msgstr[0] ""
"Зміни, внесені у документ за останню хвилину, будуть остаточно втрачені."
msgstr[1] ""
"Зміни, внесені у документ за останні %ld хвилини, будуть остаточно втрачені."
msgstr[2] ""
"Зміни, внесені у документ за останні %ld хвилин, будуть остаточно втрачені."
msgstr[3] ""
"Зміни, внесені у документ за останні %ld хвилин, будуть остаточно втрачені."
```

```
#: ../pluma/pluma-statusbar.c:352
#, c-format
msgid "There is a tab with errors"
msgid_plural "There are %d tabs with errors"
msgstr[0] "Вкладка з помилками"
msgstr[1] "%d вкладки з помилками"
msgstr[2] "%d вкладок з помилками"
msgstr[3] "%d вкладок з помилками"
```

**Comment by monsta** [comment]
Ok, try https://github.com/mate-desktop/pluma/pull/513 for a fix.

**Comment by raveit65** [comment]
@yetist 
Can you please fix the issue in your way with adding `/* xgettext:no-c-format */` to .pot file and removing format-c from .mo files ?
I want to avoid to remove the translated string for all other languages which will happen with https://github.com/mate-desktop/pluma/pull/513

**Comment by raveit65** [comment]
> I don't know how to make name properties in Tag translatable, the string is Abbreviated form.

Sometimes a look at gedit repo at gitlab helps. I guess gedit is ported to gettext.

**Comment by yetist** [comment]
https://github.com/mate-desktop/pluma/blob/a6fe4f45de0c90b48f51ec459ef10c007eb9c49e/po/it.po#L762-L768

Typing error make it.po fail. `&ld` should be `%ld`.

**Comment by yetist** [comment]
> @yetist
> Can you please fix the issue in your way with adding `/* xgettext:no-c-format */` to .pot file and removing format-c from .mo files ?

Done with a46ab61, after this, I think there is only one error from it.po.

**Comment by yetist** [comment]
@raveit65 

Sadly, gedit droped the tag list plugin.

https://github.com/GNOME/gedit/commit/c7cf365c268fc90b012fd1420bb1826402286d91
https://github.com/GNOME/gedit-plugins/commit/7f700d32802a526e4f02f41b2ec776380bba39f8

**Comment by sc0w** [comment]
@yetist 

> Typing error make it.po fail. &ld should be %ld.

It was already fixed at transifex

**Comment by sc0w** [comment]
I don't agree with removing `format-c`, the `uk` and `ru` translations are wrong and it doesn't fix it. (see https://github.com/mate-desktop/eom/pull/245#issuecomment-553187105 )

**Comment by raveit65** [comment]
> I don't agree with removing format-c, the uk and ru translations are wrong and it doesn't fix it. (see mate-desktop/eom#245 (comment) )

https://github.com/mate-desktop/pluma/pull/513 will drop translations for other languages eg. `de`, `fr` and a lot of others. I posted the links already.
But for you, broken french translation https://github.com/mate-desktop/eom/commit/f620f3ddc9f7b6161b4a15610df076fc0eb8559e#diff-42793ab00dcd448b33776fc86e5eaaf4R1263
An i fixed `de` translation yesterday.
Again, it is not acceptable to broke  a lot of other translations for only fixing 2 languages.
Please let us test the fix from here.

**Comment by raveit65** [comment]
Rebase with fixed `it` and `uk` translation from master.
@sc0w did forget to pull and commit his fixes from transifex at master.

**Comment by sc0w** [comment]
@raveit65 

if you remove `format-c`, in the future we can't see translation problems, for example if source have `%d` and translator use `$d` , the errors are ignored, and it can make unexpected behavior.

> Again, it is not acceptable to broke a lot of other translations for only fixing 2 languages.

It doesn't break other translations, it just add a little more work to translators, and I think they are happy doing the job. Is acceptable to have wrong translations in two languages forever?

> @sc0w did forget to pull and commit his fixes from transifex at master.

I just was waiting for https://github.com/mate-desktop/pluma/pull/513 to be merged

@mate-desktop/core-team I think we can vote, do you like to remove `format-c` and ignore all the `gettext` errors?

**Comment by yetist** [comment]
I think we should do things with the right way. If it is wrong, then we will correct it instead of ignoring it.
So, if msgstr[0] in po removes %d is wrong, then we should add it instead of removing c-format to ignore it.

**Comment by sc0w** [comment]
@mate-desktop/core-team 

I think the right way, to make everybody happy, is don't change ngettext code, fix it at transifex, and ignore de wrong error in transifex.

**Comment by raveit65** [comment]
Sigh,
all i know is that singular form of translation was removed from german and french and a lot of other  languages in eom.
It looks like that `%d` was added to singular form in eom.

I only asked to test the the other way of fixing the problem in PR.
But it seems this is too much for a straight guy like you.
Always asking for a vote from people is not the right way to argument and working together
But feel free to work alone on this PR and others if you know it better.
I am out.

**Comment by sc0w** [comment]
I fixed `ru` at transifex

but I couldn't fix ukranian (uk)



I click in Save changes, but it never saves.

I will tried to contact to transifex team, but they doesn't reply by mail, and I don't know how to register to open new thread in https://community.transifex.com/c/translators-community

**Comment by monsta** [comment]
>  Again, it is not acceptable to broke a lot of other translations for only fixing 2 languages.

List of languages with one of the plural forms in `msgstr[0]` (where the formula returns 0):
`be`, `bs`, `hr`, `lt`, `lv`, `ru`, `sl`, `sr`, `sr@latin`, `uk`.

**Comment by yetist** [comment]
This PR is done, waiting for the fix of ru.po and uk.po.

**Comment by sc0w** [comment]
@mate-desktop/core-team  maybe we must to migrate from `transifex` to other alternative?

**Comment by sc0w** [comment]
transifex issue was reported in 2013! here: https://github.com/transifex/transifex/issues/287

**Comment by monsta** [comment]
Check out README.md there, that repo isn't maintained for years...

**Comment by sc0w** [comment]
oops, yes, seems the issue never will be fixed in transifex

**Comment by monsta** [comment]
Maybe try https://www.transifex.com/contact/?

**Comment by sc0w** [comment]
The job is done!

I downloaded the .po file from transifex, modify, and later I uploaded it.



@monsta Please check if is ok for you

**Comment by monsta** [comment]
It's ok as a quickfix, but the same can happen with other languages I've mentioned when they'll get the translation for these strings.

**Comment by sc0w** [comment]
@monsta 

> It's ok as a quickfix, but the same can happen with other languages I've mentioned when they'll get the translation for these strings.

Yes, and we can again download-fix-upload, I think change code to make happy transifex which doesn't work as expected is a bad idea. In the future, if transifex don't like to fix the issue we can consider alternatives (maybe https://crowdin.com ?)

**Comment by yetist** [comment]
@monsta 

> @yetist: same as in [mate-desktop/eom#245 (comment)](https://github.com/mate-desktop/eom/pull/245#issuecomment-552183013)

Not our problem, there is discussion here.
https://lists.gnu.org/archive/html/bug-gnu-utils/2006-11/msg00139.html

**Comment by sc0w** [comment]
@yetist I see this warning in logs:

`/usr/bin/xgettext: warning: file 'pluma/pluma-ui.xml' extension 'xml' is unknown; will try C`

**Comment by monsta** [comment]
@yetist: oh, great. So the discussion went nowhere and then https://bugs.debian.org/400453 was archived in 2007...

Ok, I get it about `.gmo` files. I've also found that `make maintainer-clean` removes them. But other generated files are never cleaned.
```
monsta@asylum:~/mate/mate-session-manager$ LC_ALL=C git status po 
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	po/Makefile.in.in
	po/Makevars.template
	po/Rules-quot
	po/boldquot.sed
	po/en@boldquot.header
	po/en@quot.header
	po/insert-header.sin
	po/mate-session-manager.pot
	po/quot.sed
	po/remove-potcdate.sin

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by raveit65** [comment]
@yetist 
Several desktop files of modules have `Icon` entries. Can you please add translator hints?
```
+#: plugins/filebrowser/filebrowser.plugin.desktop.in:8
+msgid "system-file-manager"
+msgstr ""

+#: plugins/pythonconsole/pythonconsole.plugin.desktop.in:8
+msgid "text-x-python"
+msgstr ""

+#: plugins/quickopen/quickopen.plugin.desktop.in:8
+msgid "document-open"
+msgstr ""

+#: plugins/sort/sort.plugin.desktop.in:7
+msgid "view-sort-ascending"
+msgstr ""

+#: plugins/spell/spell.plugin.desktop.in:7
+msgid "tools-check-spelling"
+msgstr ""

+#: plugins/trailsave/trailsave.plugin.desktop.in:7
+msgid "edit-cut"
+msgstr ""
```
pluma-plugin.desktop.in has an `Icon` entry too, but i don't find the `msgid` in new pluma.pot resource.

**Comment by raveit65** [comment]
offtopic on
Looks like there is an issue in python code (not related to PR), i get this warning when gettext creates the pluma.pot file.
```
plugins/snippets/snippets/Placeholder.py:609: warning: 'msgid' format string with unnamed arguments cannot be properly localized:
                                                       The translator cannot reorder the arguments.
                                                       Please consider using a format string with named arguments,
                                                       and a mapping instead of a tuple for the arguments.
```
offtopic off

**Comment by raveit65** [comment]
Hmm, this happens when i select the tag-list plugin in sidebar.
```
[rave@mother ~]$ pluma 

** (pluma:22512): WARNING **: 16:04:57.491: The tag list file '/usr/share/pluma/plugins/taglist/HTML.tags.gz' is of the wrong type, was 'comment', 'Tag' expected.

** (pluma:22512): WARNING **: 16:04:57.491: The tag list file '/usr/share/pluma/plugins/taglist/HTML.tags.gz' is of the wrong type, error parsing TagGroup 'XHTML 1.0 - Tags'.

** (pluma:22512): WARNING **: 16:04:57.491: The tag list file '/usr/share/pluma/plugins/taglist/HTML.tags.gz' is of the wrong type, was 'comment', 'Tag' expected.

** (pluma:22512): WARNING **: 16:04:57.491: The tag list file '/usr/share/pluma/plugins/taglist/HTML.tags.gz' is of the wrong type, error parsing TagGroup 'HTML - Tags'.
```
This doesn't happen without PR.

**Comment by raveit65** [comment]
Approved by 2 peoples is enough.

**Pull request merged**
