### PR TITLE
Python 3

### PR DESCRIPTION
**Pull request by monnerat**
This large PR converts Pluma Python interface and its embedded plugins to Python 3.
It also fixes some Python code bugs and improves removing (although not completely) of Gtk 3 deprecated stuff in Python sources/UIs.

Thanks for considering it.

### CODE REVIEW

**Comment by yetist** [comment]
Thank you for migrating the plugin for pluma from python2 to python3.
However, this PR is too big to be reviewed. 
`42 files changed, 7014 insertions(+), 7113 deletions(-)
`

Can you split this PR into several small PRs? For example, by plugin, they are externaltools, pythonconsole, quickopen and snippets, and maybe another PR for common change.

**Comment by lukefromdc** [comment]
These are the translation warnings I got:
```

Warning: Could not merge ca translation for msgid:
Choose <menuchoice><guisubmenu>Accessories</guisubmenu><guimenuitem>Text Editor</guimenuitem></menuchoice>.
Warning: Could not merge uk translation for msgid:
<revnumber>pluma Manual V2.6</revnumber> <date>September 2003</date> <_:revdescription-1/>
Warning: Could not merge fr translation for msgid:
Select the <guilabel>Insert spaces instead of tabs</guilabel> option to specify that <application> pluma</application> inserts spaces instead of a tab character when you press the <keycap>Tab</keycap> key.
Warning: Could not merge fr translation for msgid:
<literal>$(<replaceable>cmd</replaceable>)</literal> is replaced by the result of executing <replaceable>cmd</replaceable> in a shell.
Warning: Could not merge hu translation for msgid:
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU Free Documentation License (GFDL), Version 1.1 or any later version published by the Free Software Foundation with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. You can find a copy of the GFDL at this <_:ulink-1/> or in the file COPYING-DOCS distributed with this manual.
```

**Comment by monnerat** [comment]
@yetist 
Thanks for your comment.
The first commit of this PR normalizes Python indenting to `ts=4` and strips trailing spaces. It does not change the effective code and affects ~5800 lines. This explains why the PR is so large.

As this commit can be standalone, would it be satisfactory to you to have it alone in a first PR, then a second PR with effective code change commits (as they have to be applied together) ?

@lukefromdc 
Thank you for your tests and reporting.
I do not get the translation warnings you report: maybe this is the same problem as the https://github.com/mate-desktop/mate-user-guide/issues/25 discussion you participated to? In any case, this PR does not affect the help files at all and if you get these warnings with the PR applied, you should also have them without it.

The other failures you report look very similar to what I got when starting to work on this: are you sure the new Python files are used? I suspect your Pluma binary finds old files first (All 4 Python plugins work well here when installed in the F29 systems dirs).

To test the snippets (example):

- Enable the plugin.
- Edit a `test.c` file.
- In the editing window, type `if<tab>`: it should complete a full if statement.
- Type the condition expression, then `<tab>`: it moves the cursor to the if inner statement part.

**Comment by lukefromdc** [comment]
All I get on the snippets test (with my old Pluma fully removed) is the just-typed text disappearing. As I said though I have zero understanding of its use.

**Comment by lukefromdc** [comment]
As of now, in the "view" menu "Bottom Pane" is greyed out, the statusbar shows up fine, but I have no way to bring up the python console as a result of this.

**Comment by monnerat** [comment]
> ... with my old Pluma fully removed ...

Just to be sure: did you also remove Python cache files (`*.py[co] `and `__pycache__ `dirs) ?

**Comment by lukefromdc** [comment]
I really don't know: I removed my locally packed Debian package which does NOT install those (lots of bugs in Checkinstall) so it my be that I cannot really do a valid test and possibly my results should be ignored. I am no expert on python, so if these were ever installed by make install on a previous test of pluma with python 2 plugins I would need filenames just to find them.

I don't normally use any python plugins in Pluma but have been interested in this work because I am trying to get rid of as much of python2 as possible for space and obsolescenece reasons and this is part of getting python2 out of MATE.

**Comment by raveit65** [comment]
> The first commit of this PR normalizes Python indenting to ts=4 and strips trailing spaces. It does not change the effective code and affects ~5800 lines. This explains why the PR is so large.

As this commit can be standalone, would it be satisfactory to you to have it alone in a first PR, then a second PR with effective code change commits (as they have to be applied together) ?

@monnerat 
That would be great. Let see how huge the PR is after you split out this commit.
Dunno if it is possible to build and test only one remaining plugin.

**Comment by monnerat** [comment]
> As this commit can be standalone, would it be satisfactory to you to have it alone in a first PR,...

New PR for reindenting Python files: https://github.com/mate-desktop/pluma/pull/430

>  ... then a second PR with effective code change commits (as they have to be applied together)?

Splitting other commits would require to rework them to retain Python 2 compatibility, in order to not have things not working between applying them...

**Comment by monnerat** [comment]
@selectiveduplicate 
Many thanks for your report.

> I've had a little problem with the console plugin; I get the following warnings in the terminal when I press the preferences button for the plugin: ...

The language property seems not supported by your gtk version. As it is not very important, I have removed it now in commit https://github.com/mate-desktop/pluma/pull/425/commits/d243690e332e3ac726c6eef879f9180cf11df3f9. Maybe you can recheck with this.

> The external tools plugins offer a "search" script to search in text files. When I run that command, the "search in text files" dialog doesn't pop up over my current window, I have to minimize pluma to see it; it doesn't show up on the list of windows too.

Yes, I noted that too and googled for it. The reason is: the popup is controlled by the zenity external program and is not under our control. The problem already occurs with the current Python 2 version (the current PR does not pretend fixing all plugins problems!). There is a dirty workaround involving the `wmctrl` program at https://unix.stackexchange.com/questions/152294/keep-a-zenity-dialog-box-always-on-top-in-foreground. If someone is interested in fixing it, external tools shell scripts should be updated (`Run command` suffers the same problem).

> After completing the search, or if I cancel the search, I get the following in my terminal: ...

Strange! I do not get it and checked `g_child_watch_source_new` documentation as advised: it seems to me the code is conformant. In addition, nothing has been changed in the subprocess/pipe logic. Maybe you should check if this is new or if you already have it without the PR applied. I suspect this is a GLib version problem.

Thanks again for your testing.

**Comment by raveit65** [comment]
I have merged https://github.com/mate-desktop/pluma/pull/430
So this PR needs a rebase from master.

**Comment by monnerat** [comment]
Rebase done: PR size reduced to ~ +/-1500 lines !

**Comment by monnerat** [comment]
I have split the remaining commits and updated the code to be Python 2 & 3 compatible. The new pull requests are:
https://github.com/mate-desktop/pluma/pull/433
https://github.com/mate-desktop/pluma/pull/434
https://github.com/mate-desktop/pluma/pull/435
https://github.com/mate-desktop/pluma/pull/436

When they will be pulled to master, a 5th one will convert Pluma itself to use Python 3.

As a consequence, I close the current PR.

**Pull request closed without merging**
