### PR TITLE
Require gtk+ 3.22 in glade files

### PR DESCRIPTION
**Pull request by tamplan**

### CODE REVIEW

**Comment by raveit65** [comment]
Those required versions are only used by a internal deprecation check in glade.
Why you want to change it?

**Comment by tamplan** [comment]
Hi,

I have seen this PR https://github.com/mate-desktop/engrampa/pull/376 and i have thinking only to help.

The configure.ac file contents "GTK_REQUIRED=3.22.0" and i have thinking it will better like this.

I don't know is this PR (and all others like this) is needed or not.

Regards

**Comment by raveit65** [comment]
I only want to make sure that you know for what this require i needed and why you see gtk+-3.20 in glade files.
With latest glade-3.22.2 in fedora 32: (Toolkit version required)
Bildschirmfoto zu 2020-05-16 16-32-23
Glade will always update the file with 3.20.
So, i am not sure if this is needed, but it doesn't hurt :smile: 

@sc0w 
feel free to merge it and all other PRs.
No need for second reviewer.

**Comment by rbuj** [comment]
@tamplan Did you check that the ui files have no deprecated widgets or version mismatches on clicking on the Verify button?

**Comment by sc0w** [comment]
@raveit65 

> I only want to make sure that you know for what this require is needed and why you see gtk+-3.20 in glade files.

I think because glade developers did't upgrade the gui to show 3.22 there

**Comment by tamplan** [comment]
> @tamplan Did you check that the ui files have no deprecated widgets or version mismatches on clicking on the Verify button?

Now yes on my Ubuntu 20.04 glade version 3.22.2, the file 'snippets.ui' give me notice for the 'source_buffer' widget.

Damned!

**Comment by tamplan** [comment]
The file 'snippets.ui' with `<requires lib="gtk+" version="3.0"/>` give me the same notice with glade...

**Comment by rbuj** [comment]
@tamplan The warning about "Invalid object type" is not related with your pull request.
```
$ find . -name *.ui -exec echo {} \; -exec gtk-builder-tool validate {} \;
./pluma/dialogs/pluma-encodings-dialog.ui
./pluma/dialogs/pluma-preferences-dialog.ui
./pluma/dialogs/pluma-search-dialog.ui

(gtk-builder-tool:14024): Gtk-WARNING **: 18:12:39.557: Failed to set property GtkButtonBox.layout-style to : Could not parse enum: ''
./pluma/pluma-print-preferences.ui
./plugins/time/pluma-time-setup-dialog.ui
./plugins/time/pluma-time-dialog.ui
./plugins/snippets/snippets/snippets.ui
./plugins/snippets/snippets/snippets.ui:283:1 Invalid object type 'PlumaView'
./plugins/externaltools/tools/outputpanel.ui
./plugins/externaltools/tools/tools.ui
./plugins/externaltools/tools/tools.ui:6:1 Invalid object type 'PlumaDocument'
./plugins/sort/sort.ui
./plugins/docinfo/docinfo.ui
./plugins/pythonconsole/pythonconsole/config.ui
./plugins/spell/languages-dialog.ui
./plugins/spell/pluma-spell-setup-dialog.ui
./plugins/spell/spell-checker.ui
```

**Comment by raveit65** [comment]
Why not merging when you approve such a simple version change? :smile: 
This doesn't have any effect for building or runtime.....

**Pull request merged**
