### PR TITLE
nocomments plugin

### PR DESCRIPTION
**Pull request by alexeyneu**

### CODE REVIEW

**Comment by sc0w** [comment]
An understandable commit message is needed

**Comment by alexeyneu** [comment]
base is copypasted from changecase plugin

**Comment by raveit65** [comment]
> plugin that alter line comments.

to what?

more words you write --> more chances that you're understandable.

**Comment by alexeyneu** [comment]
@raveit65 you have an issue that describes all this stuff. So i do not understand and do not care why you need it. You can create your own commit and cherry-pick mine .

**Comment by alexeyneu** [comment]
"<Control><Shift>b"

**Pull request closed without merging**
