### PR TITLE
Redesign Pluma Preferences Dialog

### PR DESCRIPTION
**Pull request by mbkma**
Reason for PR: Preferences Dialog in master is very tall with the new options. I imagine this to be problematic on small displays.

- ~~Group text appearance preferences together in order to make dialog less tall.~~
- Remove empty labels and use widget margins instead.
- In "Show Spaces,...": Indent subitems a little more
- Indent "Do not split words.." box in "Text Wrapping" (Because its a subitem. I am not sure about this one though.)
- Do not indent box with colour schemes
- Capitalize headings (Grid pattern -> Grid Pattern and Show spaces, tabs, newlines -> Show Spaces, Tabs, Newlines). See https://headlinecapitalization.com/

Edit:
The following additional changes were done:
- Group options into Display and Highlighting categories
- Fix sensitivity of auto-save spinbutton
- Display right margin with spinbutton in one line
- Apply sensitivity on spinbutton directly instead of according ui objects "autosave_hbox" and "right_margin_position_hbox"
- Adjust order of "Spaces, Tabs, Newlines" checkboxes to match the headings order

### CODE REVIEW

**Comment by rbuj** [comment]
I agree with everything except the first group of options Text Appearance, which groups two highlighting options with displaying the line number.

### Before

Screenshot at 2020-10-04 10-15-27

### After

Screenshot at 2020-10-04 10-25-46

**Comment by mbkma** [comment]
another suggestion:

Screenshot at 2020-10-04 15-29-10

**Comment by rbuj** [comment]
> another suggestion:

Yes, it looks better now.

**Review by rbuj — COMMENTED** [review]
the spacing is not always the same in the boxes (1/3/6/10/16 px):
```diff
diff --git a/pluma/dialogs/pluma-preferences-dialog.ui b/pluma/dialogs/pluma-preferences-dialog.ui
index d4c8b1e..aaf0811 100644
--- a/pluma/dialogs/pluma-preferences-dialog.ui
+++ b/pluma/dialogs/pluma-preferences-dialog.ui
@@ -133,7 +133,7 @@
                         <property name="can_focus">False</property>
                         <property name="margin_start">10</property>
                         <property name="orientation">vertical</property>
-                        <property name="spacing">3</property>
+                        <property name="spacing">6</property>
                         <child>
                           <object class="GtkCheckButton" id="wrap_text_checkbutton">
                             <property name="label" translatable="yes">Enable text _wrapping</property>
@@ -207,7 +207,7 @@
                         <property name="can_focus">False</property>
                         <property name="margin_start">10</property>
                         <property name="orientation">vertical</property>
-                        <property name="spacing">10</property>
+                        <property name="spacing">6</property>
                         <child>
                           <object class="GtkCheckButton" id="highlight_current_line_checkbutton">
                             <property name="label" translatable="yes">Highlight current _line</property>
@@ -280,7 +280,7 @@
                         <property name="can_focus">False</property>
                         <property name="margin_start">10</property>
                         <property name="orientation">vertical</property>
-                        <property name="spacing">16</property>
+                        <property name="spacing">6</property>
                         <child>
                           <object class="GtkCheckButton" id="display_line_numbers_checkbutton">
                             <property name="label" translatable="yes">_Display line numbers</property>
@@ -721,7 +721,7 @@
                         <property name="can_focus">False</property>
                         <property name="margin_start">10</property>
                         <property name="orientation">vertical</property>
-                        <property name="spacing">1</property>
+                        <property name="spacing">6</property>
                         <child>
                           <object class="GtkBox" id="hbox1">
                             <property name="visible">True</property>
```

**Comment by mbkma** [comment]
@rbuj thanks for the review, I think it is fixed now

**Review by rbuj — COMMENTED** [review]
You can remove hbox141 and rename vbox205 to tabs_width_hbox.
missing spacing property in show_spaces_tabs_newlines_vbox.
```diff
diff --git a/pluma/dialogs/pluma-preferences-dialog.ui b/pluma/dialogs/pluma-preferences-dialog.ui
index a71856b..876045a 100644
--- a/pluma/dialogs/pluma-preferences-dialog.ui
+++ b/pluma/dialogs/pluma-preferences-dialog.ui
@@ -720,6 +720,7 @@
                         <property name="can_focus">False</property>
                         <property name="margin_start">10</property>
                         <property name="orientation">vertical</property>
+                        <property name="spacing">6</property>
                         <child>
                           <object class="GtkCheckButton" id="draw_spaces_checkbutton">
                             <property name="label" translatable="yes">Show _spaces</property>
```

**Review by rbuj — APPROVED** [review]
LGTM

**Comment by mbkma** [comment]
Just fixed an a11y issue.

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine, the new preferences dialog "view" tab is nicely rearranged and none of the items are missing (feature parity w old version). Didn't get any runtime warnings in terminal on opening the preferences dialog. 

After dropping these files into a previous build, I got these build warnings but I think they do NOT relate to this PR as they are from other files entirely, probably they were rebuilt as a result of replacing the files this PR changes:

```
pluma-utils.h:61: Warning: Pluma: symbol='menu_popup_at_treeview_selection': Unknown namespace for symbol 'menu_popup_at_treeview_selection'
pluma-utils.h:81: Warning: Pluma: symbol='g_utf8_caselessnmatch': Skipping foreign symbol from namespace Gio
pluma-utils.h:45: Warning: Pluma: symbol='GBOOLEAN_TO_POINTER': Unknown namespace for symbol 'GBOOLEAN_TO_POINTER'
pluma-utils.h:46: Warning: Pluma: symbol='GPOINTER_TO_BOOLEAN': Unknown namespace for symbol 'GPOINTER_TO_BOOLEAN'
pluma-utils.h:48: Warning: Pluma: symbol='IS_VALID_BOOLEAN': Unknown namespace for symbol 'IS_VALID_BOOLEAN'
pluma-document.c:1549: Warning: Pluma: pluma_document_load: unknown parameter 'doc' in documentation comment, should be 'document'
pluma-commands-file.c:334: Warning: Pluma: pluma_commands_load_uris: argument uris: Missing (element-type) annotation
pluma-utils.h:161: Warning: Pluma: pluma_image_menu_item_new_from_pixbuf: return value: Missing (transfer) annotation

```
Since these are from other files, this is probably good to go

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
