### PR TITLE
double click to the right of the last open tab to open a new tab

### LINKED ISSUE #185: Double click to the right of the last open tab to open a new tab
like firefox, double click to the right of the last open tab to open a new tab

image3398
## 

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35087330-double-click-to-the-right-of-the-last-open-tab-to-open-a-new-tab?utm_campaign=plugin&utm_content=tracker%2F1179776&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1179776&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by sc0w**
New feature

Fixes #185

### CODE REVIEW

**Comment by raveit65** [comment]
Ok, i see no problems here, so i will merge it to master and use it for 1.18 in fedora-26 as patch.

**Comment by raveit65** [comment]
merge3d https://github.com/mate-desktop/pluma/commit/5bed2111c37a1d39eaf7cdad489bd954b5f06227
Thank you

**Comment by raveit65** [comment]
@sc0w 
I noticed a build warning
```
pluma-notebook.c: In function 'button_press_cb':
pluma-notebook.c:643:47: warning: passing argument 1 of 'gtk_notebook_get_current_page' from incompatible pointer type [-Wincompatible-pointer-types]
    tab1click = gtk_notebook_get_current_page (notebook);
                                               ^~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:151:0,
                 from pluma-notebook.c:44:
/usr/include/gtk-3.0/gtk/gtknotebook.h:179:12: note: expected 'GtkNotebook * {aka struct _GtkNotebook *}' but argument is of type 'PlumaNotebook * {aka struct _PlumaNotebook *}'
 gint       gtk_notebook_get_current_page (GtkNotebook *notebook);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pluma-notebook.c:648:53: warning: passing argument 1 of 'gtk_notebook_get_current_page' from incompatible pointer type [-Wincompatible-pointer-types]
    if ((tab1click != gtk_notebook_get_current_page (notebook)) ||
                                                     ^~~~~~~~
In file included from /usr/include/gtk-3.0/gtk/gtk.h:151:0,
                 from pluma-notebook.c:44:
/usr/include/gtk-3.0/gtk/gtknotebook.h:179:12: note: expected 'GtkNotebook * {aka struct _GtkNotebook *}' but argument is of type 'PlumaNotebook * {aka struct _PlumaNotebook *}'
 gint       gtk_notebook_get_current_page (GtkNotebook *notebook);
```
But editing this part in pluma-notebook.c to
```
	if (event->button == 1)
	{
		if (event->type == GDK_BUTTON_PRESS)
		{
			tab1click = gtk_notebook_get_current_page (GTK_NOTEBOOK (notebook));
			newfile = (tab_clicked == -1);
		}
		else if (event->type == GDK_2BUTTON_PRESS)
		{
			if ((tab1click != gtk_notebook_get_current_page (GTK_NOTEBOOK (notebook))) ||
			    (tab_clicked >= 0) || ((tab_clicked == -1) && (!newfile)))
				return TRUE;

			newfile = FALSE;
		}
	}
```
fixes the build warnings. And the new function is working.
What do you think?

**Comment by sc0w** [comment]
@raveit65 yes, I agree, sorry

**Comment by raveit65** [comment]
np, i was happy to found a solution.
https://github.com/mate-desktop/pluma/commit/54992c3d01bd58baa33320c96446c13c55329814

**Pull request closed without merging**
