### PR TITLE
pluma-view: Fix: Don't loss the PRIMARY clipboard

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/pluma/issues/179

### CODE REVIEW

**Comment by lukefromdc** [comment]
With my fingers, a way to empty this buffer, select NULL, or simply disable middle click paste is absolutely necessary. Worst case I can patch Pluma locally to remove it, but any way of emptying the buffer when deselecting text does not do it will be good enough for me. I had to disable almost all the middlemouse click features in Firefox for similar reasons on my boxes.

Maybe a gsettings option if there is not already a way to empty the buffer?

**Comment by lukefromdc** [comment]
GNOME does have the ability (in gnome-tweak-tool's "keyboard and mouse" to enable or disable middle click paste. Maybe we could add that to M-C-C?

**Comment by sc0w** [comment]
@lukefromdc  I will tray to do something in other PR

**Comment by lukefromdc** [comment]
I am now looking at 
https://github.com/GNOME/gnome-settings-daemon/commit/aad836ebcbf2a20f72188ced1cc8fe33da6d39ac#diff-98eb5b265d77a75d070ec322831ebe58
 from gnome-settings-daemon as a possible way to fix this issue for myself and anyone else needing to be able to turn middlemouse paste on and off. Default should be ON as that is the normal Xorg default(this is not available in Wayland at all). When I have it ready I will submit a PR and test it with Pluma and this PR applied

**Comment by lukefromdc** [comment]
Also turn out adding 
gtk-enable-primary-paste=false
to ~/.local/gtk-3.0/settings.ini will turn this off, I just confirmed this to work by testing. Now let's see if that GNOME commit works and lets dconf-editor do it, if so we can then look at a GUI checkbox for m-c-c

**Comment by lukefromdc** [comment]
Meanwhile I withdraw all objections to this PR as the problem has an existing solution

**Comment by lukefromdc** [comment]
Please test
https://github.com/mate-desktop/mate-desktop/pull/332
and
https://github.com/mate-desktop/mate-settings-daemon/pull/234
together, they allow enabling or disabling middlemouse paste from dconf-editor. Default is "enabled" to avoid any change in expected behavior with a default install.

**Comment by lukefromdc** [comment]
Also please test 
https://github.com/mate-desktop/mate-control-center/pull/369
which adds a checkbox in mate-control-center>mouse to enable(default) or disable middlemouse paste

**Pull request merged**
