### PR TITLE
pluma-view: Fix: Bold and Italic fonts don't work

### PR DESCRIPTION
**Pull request by sc0w**
culprit commit: https://github.com/mate-desktop/pluma/commit/310bfc249aac3dd80511d3dade14aa06f3d9769a (my fault)

Since that commit bold and italic fonts don't work

This is the fix

### CODE REVIEW

**Comment by lukefromdc** [comment]
We also get this new warning running from terminal from this commit, not present in master:

```
(pluma:18525): Gtk-WARNING **: 17:47:24.192: Theme parsing error: <data>:1:17: not a number

(pluma:18525): Gtk-WARNING **: 17:47:24.192: Theme parsing error: <data>:1:27: Using Pango syntax for the font: style property is deprecated; please use CSS syntax


```

**Comment by sc0w** [comment]
warnings fixed with latest changes

@lukefromdc please test again

**Comment by lukefromdc** [comment]
OK, I con confirm that a build with the latest change no longer throws the runtime warnings I got last time, and bold and italic fonts work

**Comment by sc0w** [comment]
more changes, now the system font works if it is in px ("Monospace 10px" for example)

**Comment by lukefromdc** [comment]
I just retested and can confirm that this makes system bold and italic monospace fonts work, also makes same fonts selected from within Pluma itself work, and does not throw any warnings. Seems to be ready to go

**Pull request merged**
