### PR TITLE
preferences: enable the plugin 'sort' by default

### PR DESCRIPTION
**Pull request by HacKurx**
Hi,

The "sort" plugin is widely used by users, let's enable it by default.

Thank you.

Best regards.

### CODE REVIEW

**Comment by raveit65** [comment]
Not sure, because it can't be undo when done by accidental.
The only way to undo a sorting is not to save the file, but in this case you can lost other changes.
@mate-desktop/core-team 
Thoughts?

**Comment by lukefromdc** [comment]
I think enabling by default a plugin whose effects cannot be undone is not a good idea unless and until that plugin can be made to support undo.

**Comment by Yetoo1** [comment]
> Since there's a warning on the sort plugin dialogue saying that this can't be undone, I don't think this is going to cause any issue.

Even then, I don't think so since it seems rather incomplete even if it does say it can't be undone. It would be great if a complete feature could exist before pushing it as default to reduce possibility of pushing now, a problem comes up, then a dilemma that comes whether to remove the feature because of the problem or actually fix it and I would hate the decision to remove it (while seemingly unlikely here, I've seen many other projects where smaller problems result in feature removal) because it would be adding unnecessary clicks. It would be great if that path were to be avoided all together by shipping the plugin as default when it is complete. Just my input.

**Comment by HacKurx** [comment]
Hello to all,

Reading the Mate 1.26 changelog for pluma: "The sort plugin now supports undo actions."
To this end, can you please survey your users or study this merge request?

Thanks.

**Comment by raveit65** [comment]
Why should this be a default setting?
I don't think that all users of pluma like to use it.
You can enable it for your self if you need it.

**Comment by mbkma** [comment]
I agree, we should not enable more plugins by default, unless there is a good reason to do so.

**Pull request closed without merging**
