### PR TITLE
tab: restore the cursor and scroll in an idle.

### PR DESCRIPTION
**Pull request by sleeveroller**
mate-desktop/pluma#184

I found this commit in the gedit git repository which seems to fix this problem so I've ported it to pluma:

(https://github.com/GNOME/gedit/commit/cb5829d81cd5a48e471ce526e3dd01842a80b703)

From my testing it looks like the cursor was being correctly positioned but depending on the timing it would not always scroll down to the cursor. This change basically waits to make sure the tab is loaded properly before scrolling down to the cursor.

### CODE REVIEW

**Comment by raveit65** [comment]
Looks good for me with gtk3 build.
@monsta @XRevan86 
Can you do a code review please?
My results:
```
Ok, now i see the different :)
With your PR the scrolled window shows the old cursor position, w/o the cursor is at this position but you need to to type the arrow keys to show the position in the scrolled window.
Nice finder ;)
```

**Comment by monsta** [comment]
Well, I couldn't reproduce that race condition, but things seem to be ok with this PR, so I think it's alright to merge it.

**Comment by raveit65** [comment]
OK, for me it is a big improvement.

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/pluma/commit/01e91d300b73e178130cf41d5356122bb8146212
Thank you

**Pull request closed without merging**
