### PR TITLE
modelines plugin: add a shorter version of the 'textwidth' option ('tw')

### PR DESCRIPTION
**Pull request by fszymanski**

### CODE REVIEW

**Comment by raveit65** [comment]
Please rebase with master to fix CI building.

**Comment by raveit65** [comment]
I do not use the modul for myself. How can this be tested?

**Comment by fszymanski** [comment]
`modelines` allow you to set variables specific to a file. If you put the following in the last line of a Python program, you would get a textwidth of 60 chars when editing that file:
```
# vim: tw=60
```
In the case of `Pluma` the `Display right margin at column` option will be set to 60.
See: https://www.cs.swarthmore.edu/oldhelp/vim/modelines.html

**Review by raveit65 — APPROVED** [review]
LGTM,
both versions `# vim: tw=60` and `# vim: textwidth=60` are working now.

**Pull request merged**
