### PR TITLE
[ci] Add cppcheck html report

### PR DESCRIPTION
**Pull request by yetist**
Include cppcheck html report on website.

### CODE REVIEW

**Comment by sc0w** [comment]
@yetist please don't remove cppcheck in debian, I use debian to test PRs, and it is useful for me to see all the warnings in one unique log

**Comment by sc0w** [comment]
@raveit65 I noticed you don't like cppcheck logs in fedora builds, but there is no logs with this PR, and I think this is one more very useful tool for development

**Comment by raveit65** [comment]
I like to  have one build log without having tons of warnings which aren't in normal build logs,
If i need to build a PR local to have a readable build logs than all this CI isn't helpful for reviewing a PR.
I don't get why it isn't possible to do that for debian builds?
```
  - if [ ${DISTRO_NAME} == "debian" ];then
<cut>
  - fi
```

**Comment by sc0w** [comment]
@raveit65 check the logs, there are no logs in fedora with cppcheck warnings with this PR

anyway, I have no problem if it can be done in debian build

**Comment by raveit65** [comment]
So only the deployment of the ccpcheck result is done with fedora build?
I merged https://github.com/mate-desktop/mate-dev-scripts/pull/21, hope this wasn't to early.

**Comment by sc0w** [comment]
@raveit65 seems we can't see the output in `after_scripts`

btw, cppcheck doesn't build the code, it just analyze it, and the job is done in seconds

**Comment by raveit65** [comment]
https://travis-ci.org/mate-desktop/pluma/jobs/526710851#L6862
```
Skipping a deployment with the script provider because this is not a tagged commit
```
This is because of deployment for release page.
Not sure what's getting wrong here.

**Comment by sc0w** [comment]
`Skipping a deployment with the script provider because this is not a tagged commit`

I see the same in all the builds (arch/debian/fedora/ubuntu)

and I see the same in master

**Comment by yetist** [comment]
> Skipping a deployment with the script provider because this is not a tagged commit

It's ok, only tagged commit can release tarballs.

**Comment by raveit65** [comment]
I know, but where are the deployment for ccpcheck results?

**Comment by raveit65** [comment]
Ok, found it. It's a bit confusing that clang results are named with cppcheck-htmlreport/, eg. https://pluma.mate-desktop.dev/2019-05-01-125311-7610-1@ab4280e76ab6_cppcheck-htmlreport/

**Comment by sc0w** [comment]
@raveit65 

> Ok, found it. It's a bit confusing that clang results are named with cppcheck-htmlreport/, eg. https://pluma.mate-desktop.dev/2019-05-01-125311-7610-1@ab4280e76ab6_cppcheck-htmlreport/

I think `cppcheck-htmlreport` there, is the name of branch in PR

**Pull request merged**
