### PR TITLE
travis: require enchant2

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
Configure checks for enchant-2 and enchant and i built it always with enchant2-devel for fedora.
But now archlinx build failed.

**Comment by rbuj** [comment]
> But now archlinx build failed.

`make distclean` failed on arch, I guess it's due a file system error:
```
ERROR: files left in build directory after distclean:
./docs/reference/pluma.actions
```

**Comment by raveit65** [comment]
It's weird. the issue started with latest commit in master, but this was Ok in related PR from you.
I've restarted the builds, let see if they failed again.
I rectal that we had this issue in another package a while ago.

**Comment by raveit65** [comment]
Building failed again.
Anyway. maybe there is an issue with autotools in rolling archlinux at the moment.
All this isn't related to PR.
When this issue doesn't goes away we can disable distcheck for archlinux.

**Pull request merged**
