### PR TITLE
pluma-time-plugin.c: avoid 'gtk_dialog_new_with_buttons' with stock id

### PR DESCRIPTION
**Pull request by sc0w**
I have no idea how to test this PR

### CODE REVIEW

**Comment by raveit65** [comment]
Looks like that in the time-plugin-dialog from preferences an icon is missing for the close button.
As the button is translated i looks like an old issue and not related to PR.

**Comment by sc0w** [comment]
aha, finally I found the dialog:

it happens with error to load the .ui file:

time1

error_time_dialog

The PR seems to work fine here

@raveit65 

> Looks like that in the time-plugin-dialog from preferences an icon is missing for the close button.
> As the button is translated it looks like an old issue and not related to PR.

yes, by the moment, I don't know how to fix that

**Comment by raveit65** [comment]
@sc0w 
> it happens with error to load the .ui file:

Local issue or a blocker?
I don't see this problem here.

**Comment by sc0w** [comment]
@raveit65 no, there is no problems

I mean: this PR affects this dialog (the "ok" button):

error_time_dialog

to show the dialog, you need to modify the file pluma-time-dialog.ui to force the error dialog

**Comment by raveit65** [comment]
Ahh, Ok
let's merge it.

**Pull request merged**
