### PR TITLE
Gir and docs

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
I don't think that aditional testing is needed.
Some changes are from comparing with gedit commits. E.g.
```
@@ -1167,7 +1167,7 @@ pluma_document_get_short_name_for_display (PlumaDocument *doc)
 /**
  * pluma_document_set_short_name_for_display:
  * @doc:
- * @short_name: (allow-none):
+ * @name: (allow-none):
```
Other was simply suggestions from command line warnings, you should see the warnings in master. E.g.
```
@@ -227,7 +227,7 @@ pluma_message_type_is_supported (GType type)
  * @object_path: (allow-none): the object path
  * @method: (allow-none): the method
  * @num_optional: number of optional arguments
- * @var_args: key/gtype pair variable argument list
+ * @va_args: key/gtype pair variable argument list
```
So i think , they are fine.
Honestly , i don't know how to test introspections hints.

The question for the second commit is, are these gtk-doc code blocks or not?
Docs says that a gtk-doc code block looks like this 
```
/**
 *
*/
```
https://wiki.gnome.org/Projects/GTK%2B/DocumentationSyntax
So i assume that using
```
 /** comment **/
```
is just a typo and not a gtk-doc code block.

**Comment by lukefromdc** [comment]
I don't know anything about gtk-doc generation. Does this mean any code block formatted with 
/*
 *
 */

Gets pulled into auto-generated documentation if this is enabled?

**Comment by raveit65** [comment]
I understand docs like this.
If a code block looks like this
`/** comment */`
than it is marked as a gtk-doc code block, otherwise it is is a simple comment block.

**Comment by sc0w** [comment]
This PR fixes the build warnings:

```
pluma-document.c:1170: Warning: Pluma: pluma_document_set_short_name_for_display: unknown parameter 'short_name' in documentation comment, should be 'name'

pluma-message-type.c:230: Warning: Pluma: pluma_message_type_new_valist: unknown parameter 'var_args' in documentation comment, should be 'va_args'
pluma-message-type.c:323: Warning: Pluma: pluma_message_type_set_valist: unknown parameter 'var_args' in documentation comment, should be 'va_args'

pluma-prefs-manager-app.h:38: Error: Pluma: Skipping invalid GTK-Doc comment block:
/** LIFE CYCLE MANAGEMENT FUNCTIONS **/
^

pluma-prefs-manager.h:132: Error: Pluma: Skipping invalid GTK-Doc comment block:
/** LIFE CYCLE MANAGEMENT FUNCTIONS **/
^
pluma-prefs-manager.h:140: Error: Pluma: Skipping invalid GTK-Doc comment block:
/** PREFS MANAGEMENT FUNCTIONS **/
^

pluma-utils.c:718: Warning: Pluma: pluma_utils_location_get_dirname_for_display: unknown parameter 'file' in documentation comment, should be 'location'
```


More similar warnings are pending...

No additional tests are needed in my opinion.

**Pull request merged**
