### PR TITLE
bring back open file from location dialog

### LINKED ISSUE #210: Ctrl + L doesn't open a location
I was reading through the shortcuts and testing each one. This shortcut doesn't open anything. This was tested with 1.17.3 or whatever is currently in the master branch at the time of posting.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40722414-ctrl-l-doesn-t-open-a-location?utm_campaign=plugin&utm_content=tracker%2F1179776&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1179776&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mbkma**
That feature was removed from gedit [in 2009](https://gitlab.gnome.org/GNOME/gedit/commit/26c2dfbd90b2f973f8540b15be4da38216e3a70b). I know that there is an option in file-chooser-dialog to open a file from location (ctrl+l), but most people don't. And this dialog here is fast accessible and features history entries. It is mostly the same code as 2009, but with some deprecation fixes.

Screenshot at 2020-04-05 10-39-27

 Fixes #210

### CODE REVIEW

**Comment by rbuj** [comment]
IMHO it's redundant with the feature that currently offers GtkFileChooserDialog.

### Openning a location on `Open Location` dialog

Screenshot at 2020-04-16 15-22-01

### Openning a location on [GtkFileChooserDialog](https://developer.gnome.org/gtk3/stable/GtkFileChooser.html)

Screenshot at 2020-04-16 15-22-49

**Comment by rbuj** [comment]
I saw also that `Open Location` dialog is not modal, i.e. I was able to access to main caja menu once the `Open Location` dialog was displayed. It may be addressed [gtk_window_set_transient_for](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-transient-for).

**Comment by mbkma** [comment]
fair enough - closing this PR. Help Keyboard_Shortcuts should be updated though.
Screenshot at 2020-04-16 16-15-00

**Comment by raveit65** [comment]
Named `Open location` is misleading, you can only open an URI of an file with this dialog.
Eg. `/home/rave/rpmbuild/SOURCES/pluma_0001-smart-converter-Fix-memory-leaks.patch`
But using `~/rpmbuild/SOURCES/pluma_0001-smart-converter-Fix-memory-leaks.patch` doesn't work. 
It should named `open from location` which is basicly the same as with GtkFileChooser.

**Comment by rbuj** [comment]
@raveit65 I can switch between location entry and breadcrumbs with `ctrl+l`, then I can open a relative file location like `~/test.txt`.

**Comment by rbuj** [comment]
The location entry will also open if you press '.', '/' or '~'.

**Comment by raveit65** [comment]
Good that it works with GtkFileChooser, it didn't work with the dialog from PR.
Any way, PR is obsolete and closed.

**Comment by raveit65** [comment]
Ok, confirmed `crt+L` works with GtkFileChooser.
So, do we need to revert the shortcut with your new PR?
Or is this shortcut in GtkFileChooser code?
Maybe only `help` needs updating?

**Comment by raveit65** [comment]
Got it, new PR is only about `help` :)

**Pull request closed without merging**
