### PR TITLE
Fix not running gla11y when not available

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by lukefromdc** [comment]
Also, someone needs to check this (all of these) with gla11y installed and make sure it works in that case

**Comment by sthibaul** [comment]
CI did test that case

**Comment by sthibaul** [comment]
CI did test that case

**Comment by lukefromdc** [comment]
I don't yet know how to invoke the build options in Meson, which I am still learning to use. Oh yeah it's a lot faster and I don't have to deal with Checkinstall (slow and messy with files it should not pick up), but I'm still learning how to use it.

**Comment by raveit65** [comment]
@lukefromdc 
fixed by https://github.com/mate-desktop/pluma/commit/cdd098013a810ccd8b8baeef3110676f87da1fa9

**Comment by lukefromdc** [comment]
I can confirm a build of 1.23.1 (with https://github.com/mate-desktop/pluma/commit/cdd098013a810ccd8b8baeef3110676f87da1fa9) finished fine

**Pull request closed without merging**
