### PR TITLE
deprecations and warnings

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
pluma-notebook: don't use deprecated gdk_cursor_new is updated after a rebase against master.

**Comment by lukefromdc** [comment]
Rebased version also works fine

**Comment by monsta** [comment]
Since gio is a part of glib, https://github.com/mate-desktop/pluma/commit/91834ee958566d4edc2af9ecb90ac4440765c7d1 essentially bumps glib requirement to 2.37 instead of 2.36.
But... GTK+ 3.14 already requires 2.41.2 - so we're actually safe to bump the requirement to 2.42 (and drop some old code). :slightly_smiling_face:

**Comment by raveit65** [comment]
Thanks for info, i can update requirements next time but to decide which code is old and can be dropped is definitely a job for you ;-)

**Pull request merged**
