### PR TITLE
avoid deprecated GtkStock

### PR DESCRIPTION
**Pull request by sc0w**
The expected with this PR: the same icons like before

Note: I think the translations are affected, so, this is not for 1.20

### CODE REVIEW

**Comment by monsta** [comment]
It's also quite big, so maybe indeed leave it until next dev phase.

**Comment by raveit65** [comment]
Opps,
i just found this warning in ~/.xsession-errors of my test VM.
```
Traceback (most recent call last):
  File "/usr/lib64/pluma/plugins/externaltools/__init__.py", line 215, in do_activate
    bottom.add_item_with_stock_icon(self._output_buffer.panel,
AttributeError: 'Panel' object has no attribute 'add_item_with_stock_icon'
```
@sc0w 
Can you please take a look at it?

**Comment by sc0w** [comment]
@raveit65 

I didn't modify the externaltools plugin

without the PR you see the same warning?

**Comment by raveit65** [comment]
No, i never saw this warning before.
But i never use external-tools normal.
Enabling it in my normal installation generates more libpeas warnings.
So, still ignore it......

**Comment by sc0w** [comment]
I can't see that warning

anyway, I don't know why, but I can't load that plugin:

```
(pluma:23023): libpeas-WARNING **: Error importing plugin 'externaltools':
Traceback (most recent call last):
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/x86_64-linux-gnu/pluma/plugins/externaltools/__init__.py", line 21, in <module>
    from gi.repository import GObject, Gtk, Peas, Pluma
ImportError: cannot import name Pluma

(pluma:23023): libpeas-WARNING **: Error loading plugin 'externaltools'
```

**Comment by raveit65** [comment]
Hmm, i get this warning only if use this PR in this f26 test VM.
With a build from 1.20 tag i don't see that.
Maybe i have some old remnants from libeas port testing here.
...i will try to provide more debug infos.

**Comment by raveit65** [comment]
Ok, with normal plugin selection i don't get this warning.
But if i enable only 'externaltools' i get those warnings
```
Traceback (most recent call last):
  File "/usr/lib64/pluma/plugins/externaltools/__init__.py", line 215, in do_activate
    bottom.add_item_with_stock_icon(self._output_buffer.panel,
AttributeError: 'Panel' object has no attribute 'add_item_with_stock_icon'

(pluma:3464): libpeas-WARNING **: Failed to run internal Python hook 'find_extension_type':
Traceback (most recent call last):
  File "peas-python-internal.py", line 71, in call
  File "peas-python-internal.py", line 130, in find_extension_type
AttributeError: 'module' object has no attribute 'UniqueById'

(pluma:3464): libpeas-WARNING **: Failed to run internal Python hook 'find_extension_type':
Traceback (most recent call last):
  File "peas-python-internal.py", line 71, in call
  File "peas-python-internal.py", line 130, in find_extension_type
AttributeError: 'module' object has no attribute 'UniqueById'
```

**Comment by raveit65** [comment]
After enabling the 'external plugin' simply restart session, than i see only mentioned warning
```
Traceback (most recent call last):
  File "/usr/lib64/pluma/plugins/externaltools/__init__.py", line 215, in do_activate
    bottom.add_item_with_stock_icon(self._output_buffer.panel,
AttributeError: 'Panel' object has no attribute 'add_item_with_stock_icon'
```
in ~/.xsession-errors.

**Pull request merged**
