### PR TITLE
externaltools plugin: change code for Python 2 & 3 compatibility.

### PR DESCRIPTION
**Pull request by monnerat**
This rewrites the plugin in Python 3, while retaining Python 2 compatibility.

In addition, some bugs are fixed and the Gtk-3 compatibility is improved (mainly regarding UI and widget deprecation).

### CODE REVIEW

**Comment by raveit65** [comment]
With or without this PR i got this rpmbuild error.
```
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-ldconfig
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1 0
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
mangling shebang in /usr/libexec/pluma/pluma-bugreport.sh from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/build from /bin/sh to #!/usr/bin/sh
*** ERROR: ambiguous python shebang in /usr/share/pluma/plugins/externaltools/tools/switch-c: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/search-recursive from /bin/bash to #!/usr/bin/bash
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/run-command from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/remove-trailing-spaces from /bin/sh to #!/usr/bin/sh
mangling shebang in /usr/share/pluma/plugins/externaltools/tools/open-terminal-here from /bin/sh to #!/usr/bin/sh
error: Bad exit status from /var/tmp/rpm-tmp.2mDypG (%install)
```
This was with using python2 as build dependency.

**Comment by monnerat** [comment]
> *** ERROR: ambiguous python shebang in /usr/share/pluma/plugins/externaltools/tools/switch-c: #!/usr/bin/python. Change it to python3 (or python2) explicitly.

This is a Fedora/rpm packaging problem that does not occur in <= F29.
Unless the Pluma team as plans for changing the strategy about the python interpreter command naming in the shebang, I suggest you implement a Fedora-specific patch.

**Comment by raveit65** [comment]
I can use this in spec file.
```
# with python2
sed -i 's|#!\/usr\/bin/\python|#!\/usr\/bin\/python2|g' plugins/externaltools/data/switch-c.tool.in
```
But using python2 is only for testing here. My goal is to build for python3 for fedora.
Well, i didn't test if i got an error with building against python3.

**Comment by rbuj** [comment]
> This is a Fedora/rpm packaging problem that does not occur in <= F29.
> Unless the Pluma team as plans for changing the strategy about the python interpreter command naming in the shebang, I suggest you implement a Fedora-specific patch.

@raveit65 see "Using pathfix.py to fix shebangs" (spec file)
https://fedoraproject.org/wiki/Changes/Make_ambiguous_python_shebangs_error

**Comment by monnerat** [comment]
Thanks for merging :-)

**Pull request merged**
