### PR TITLE
pluma-window: have GtkRecentData on stack instead of allocating it

### PR DESCRIPTION
**Pull request by monsta**
attempt at fixing that weird regression from https://github.com/mate-desktop/pluma/pull/259#issuecomment-351084165

### CODE REVIEW

**Comment by sc0w** [comment]
@lukefromdc 

> I normally set gtk-recent-files-max-age=0

where is that?

I make the folder with the same name `recently-used.xbel` instead, and it never makes the file

@monsta it seems to work again, thanks

**Comment by lukefromdc** [comment]
gtk-recent-files-max-age=0
goes in .config/gtk-3.0/settings.ini

**Comment by monsta** [comment]
> Question: is there any chance that a local attacker on a multiuser machine could use a carefully crafted recently-used.xbel file for a stack smashing attack on this?

I don't know enough to answer this, but it's handled by GtkRecentManager, so I guess you need to look at its code...

**Comment by sc0w** [comment]
@monsta I think this is needed in the 1.18 branch too

**Comment by monsta** [comment]
Yes, forgot it. Pushed in https://github.com/mate-desktop/pluma/commit/5607600446ee672e6d49509957dcaad3cde2cefb.

**Comment by monsta** [comment]
@sc0w @sunweaver: looks like https://bugs.debian.org/883866 is about the same problem, so you can now add the patch for it.

**Comment by sc0w** [comment]
@monsta we have same problem in pluma 1.18.3 debian package

It was fixed with https://github.com/mate-desktop/pluma/commit/e0972c8dd3f95efaa9921f1567d23028325a2343 (already pushed as a patch for debian in https://anonscm.debian.org/git/pkg-mate/pluma.git/commit/?id=68991fa53827a44eb992b7fdeb0a281b0b69ea33, the upload is pending)

**Comment by monsta** [comment]
Oh, that's a different commit.

**Comment by sc0w** [comment]
yes, I mean:

we have the issue with the commit https://github.com/mate-desktop/pluma/commit/b73d6af3afced4d7c33ff02eb7c0bcc1bf54e22f and fixed with https://github.com/mate-desktop/pluma/commit/e0972c8dd3f95efaa9921f1567d23028325a2343

and we have the issue again with https://github.com/mate-desktop/pluma/commit/c776a6400df26794aecae98d73c8fb913d8d3c05 and fixed with https://github.com/mate-desktop/pluma/commit/5607600446ee672e6d49509957dcaad3cde2cefb

**Comment by monsta** [comment]
Looks like we had memory corruption somewhere... I really hope it was in the place where https://github.com/mate-desktop/pluma/commit/5607600446ee672e6d49509957dcaad3cde2cefb is.

**Pull request merged**
