### PR TITLE
python console: config.ui: avoid GtkButton:use-stock

### PR DESCRIPTION
**Pull request by sc0w**
the expected: the same look and behavior like before

### CODE REVIEW

**Comment by raveit65** [comment]
How can i execute this config-dialog for python_console?

**Comment by sc0w** [comment]
I don't know, the python console doesn't work here without/with the PR

probably this dialog shows in edit -> preferences -> plugins -> python console -> preferences button

**Comment by sc0w** [comment]
ok, if all is working like before, I will merge this PR

**Comment by sc0w** [comment]
@monsta do you know how to show this dialog?

**Pull request merged**
