### PR TITLE
Fix: selected text is lost when selecting text in other program

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/pluma/issues/217

### CODE REVIEW

**Comment by raveit65** [comment]
ohh, this PR has influences for caja.
If text is selected in pluma than the text from renaming a file or folder in caja isn't selected anymore.
I think this can drive you crazy if you work with a lot windows and workspaces, and you forgot where you did select the text.

**Comment by sc0w** [comment]
@raveit65 yes, confirmed, I will investigate it

**Comment by raveit65** [comment]
Same problem with mate-terminal.
I can't select anything if something in a pluma window is selected.

**Comment by sc0w** [comment]
@raveit65 yes, I think it affects all the gtk applications

**Comment by sc0w** [comment]
@raveit65 please test again

the behavior of this PR with the latest changes:

the selection disappears if the window lost the focus and another gtk application do one selection, and shows the selection again if the window gets the focus

**Comment by raveit65** [comment]
Semms to be Ok now.
I tested it again with 3 open windows of pluma, caja and mate-terminal and i use
```
[rave@mother ~]$ gsettings get org.mate.Marco.general auto-raise
true
```
If i select text in pluma it's possible to select text in mate-terminal and CajaCanvasItem text is selected too when renaming a file in caja.
After pluma window gets focus again the text is selected again in pluma.

If you give mate-terminal or caja focus again at this point here the text isn't select any more.
But this seems to be normal behaviour of this applications and isn't related to this PR. 

With previous version of PR i noticed also a different behaviour with coping text inside mate-terminal, with using **middle-mouse-button-for-inserting** and **Copy-marked-text-to-clipboard** is enabled .

Without the PR the actual selected text from every application will be used for coping with middle-mouse-button in mate-terminal.
If you select another text from another application this text will load in memory.

With current version of PR the selected text from pluma window will be kept always in memory for using coping with middle-mouse-button in mate-terminal, no matter if you select a text in ie. firefox.

Well this behaviour sound logic for me but can be a annoying problem if you forgot a open pluma window with selected text somewhere.
So, this needs to be discussed.
@monsta @flexiondotorg @lukefromdc @XRevan86  ^^^^

PS: Hope i wrote it understandable :-)

**Comment by sc0w** [comment]
> With previous version of PR i noticed also a different behaviour with coping text inside mate-terminal, with using middle-mouse-button-for-inserting and Copy-marked-text-to-clipboard is enabled .

yes, confirmed, it can be handled with something like this:

```
primtxt = gtk_clipboard_wait_for_text (gtk_clipboard_get (GDK_SELECTION_PRIMARY));

gtk_clipboard_set_text (gtk_clipboard_get (GDK_SELECTION_PRIMARY), primtxt, strlen (primtxt));
```

I will investigate it, and I will close this PR by the moment

**Pull request closed without merging**
