### PR TITLE
pluma-document: Fix: don't crash using files with 'bom'

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/pluma/issues/301

### CODE REVIEW

**Comment by raveit65** [comment]
review swap?

**Comment by lukefromdc** [comment]
I have no idea what that is or how to test it. A test file would allow me to test and review this

**Comment by sc0w** [comment]
@lukefromdc the mentioned issue in my first comment has a test file: https://github.com/mate-desktop/pluma/files/1841426/test.php.zip

**Comment by lukefromdc** [comment]
Error was same as with master and with gedit, I could not open the test file in any text editor except nano (in terminal).

**Comment by sc0w** [comment]
@lukefromdc please try again.

> I could not open the test file in any text editor except nano (in terminal).

It works in geany

**Comment by lukefromdc** [comment]
I teied two builfs, once with the changed file dropped into a pluma build directory, once with a new build from the git branch. Has there been a forced update to it? I am on the road now. If not, maybe GTK 3.23 is the difference? That I can test when I get home

**Comment by sc0w** [comment]
@lukefromdc I did little changes, I confirm it didn't work before, now it must work.

`== 0` is needed with `g_strcmp0` , this was my fault.

**Comment by monsta** [comment]
Ok, we react to malformed `php` with BOM at the start... what about malformed `xml` with BOM? :slightly_smiling_face: 

[bad.xml.zip](https://github.com/mate-desktop/pluma/files/2306529/bad.xml.zip)

```

**Comment by sc0w** [comment]
@monsta done!

**Comment by monsta** [comment]
Well, the point is that the problem is in `GtkSourceView`. We can try working it around for one file format, two file formats... but the actual problem is their abort.

```C
g_assert (g_slist_length (ce->priv->invalid) <= 1);
```

This is the source of the mentioned error message:
```
GtkSourceView:ERROR:gtksourcecontextengine.c:5543:update_syntax: assertion failed: (g_slist_length (ce->priv->invalid) <= 1)
```

Basically, it means: "oh, something is wrong in our **internal** structure, so let's abort the whole app that uses our library."

**Comment by lukefromdc** [comment]
A possible way to catch that would be to use a conditional check matching the assert `(g_slist_length (ce->priv->invalid) <= 1)` and whenever this returns FALSE don't run `gtk_source_buffer_set_language` rather than special casing file types

**Comment by monsta** [comment]
I don't think we have access to that, `ce->priv` is internal to the library.

**Comment by lukefromdc** [comment]
Is there anything we are sending to gtk_source_buffer_set_language other than the file type that could be used as a marker for this to detect this error?

**Comment by sc0w** [comment]
For me this is a critical bug, we can loss important files without changes, if pluma was already opened before open the 'killer' files.

@lukefromdc 

> Is there anything we are sending to gtk_source_buffer_set_language other than the file type that could be used as a marker for this to detect this error?

**UTF-8**

I mean:

`pluma test.php --encoding UTF-8` <- it crashes


`pluma test.php --encoding ISO-8859-1` <- it doesn't crash

you can see the list of encodings with:

`pluma --list-encodings`

**Comment by lukefromdc** [comment]
What would we lose if we removed gtk_source_buffer_set_language entirely? Dictionary support? Or could this be made manually selectable or otherwise made to work

**Comment by sc0w** [comment]
@lukefromdc we loss the highlighting, with this PR `php` and `xml` files with `bom` can be opened, but without the highlighting.

**Comment by sc0w** [comment]
...and `php xml` files without `bom` works the highlighting with this PR.

**Comment by lukefromdc** [comment]
OK,is there any way we could reimplement this locally? The highlighting is a crucial feature, and GTK has made some ugly choices. If not, we will just have to find and exclude all the killer file types as they come up, and leave it at that.

**Comment by sc0w** [comment]
oops, there are more formats affected, this is the complete list:

```
ASP
django template
docboox
HTML
MXML
Mallard
Markdown
MediaWiki
PHP
Tera template
XML
XSLT
```

**Comment by sc0w** [comment]
I added all the affected languages in latest changes

**Comment by lukefromdc** [comment]
At the moment I can open XML files fine, I assume this change applies only to files starting with ﻿<? ?

**Comment by lukefromdc** [comment]
Than this looks good to go

**Pull request merged**
