### PR TITLE
Fix issue #525 setting textview font css based on gedit and gtk/gtkfontbutton.c

### PR DESCRIPTION
**Pull request by BwackNinja**
Based on

https://gitlab.gnome.org/GNOME/gedit/-/commit/100b91ee49feeaf848ff1486e952d27394fcbf74

and

https://gitlab.gnome.org/GNOME/gedit/-/merge_requests/100

### CODE REVIEW

**Comment by raveit65** [comment]
Commit message needs work.
Please not use links in commit header, put them in commit body.
And use a short description what the commit does, perhaps use commit  message from gedit.
```
 Fix issue #525 setting textview font css based on gedit and gtk/gtkfontbutton.c
```
This is what you did but not a description what the commit does ;)

**Comment by BwackNinja** [comment]
Is that better? I didn't use the commit message from gedit because this change isn't about removing deprecated usage of gtk_widget_override_font like the original was.

**Comment by raveit65** [comment]
Excellent.
A meaningful commit message is important when searching in git history.
Thanks.

**Review by rbuj — COMMENTED** [review]
Test: secondary click on text [FAIL]

Untitled

**Comment by BwackNinja** [comment]
It's a bug in your theme, Clearlooks-Phenix.

Your theme is missing:

.context-menu { font: initial; }

Adwaita theme reference: https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/theme/Adwaita/_common.scss#L4709

Original commit in gtk introducing that and specifically mentioning this situation with gedit: https://gitlab.gnome.org/GNOME/gtk/-/commit/7e9372bafaeeb37dd4d8d78fff3a914731784f81

**Review by rbuj — APPROVED** [review]
LGTM

Pull request related to our themes https://github.com/mate-desktop/mate-themes/pull/279

**Review by raveit65 — APPROVED** [review]
LGTM,
builds and runs fine with our themes.

**Comment by raveit65** [comment]
@BwackNinja 
Can you do a PR for 1.24 branch please?
A simply cherry-pick doesn't work.
We can consider this as bugfix which belongs in stable branch.

**Review by lukefromdc — COMMENTED** [review]
Late review (but before this gets to a a release version): I can verify that this works fine with the relevent theme change, tested in my theme as 
https://github.com/lukefromdc/gtk-theme-ubuntustudio-legacy/commit/c50892f55bf240fa86ae9689337cd115f0547e2d

No nasty build or runtime surprises and with the above commit the context menus look as they should (no forced monospace font)

**Pull request merged**
