### PR TITLE
UI GTK3: use a size request for time plugin dialog window

### PR DESCRIPTION
**Pull request by NiceandGently**
this fixes the not selectable scrolled box in date plugin dialog window

### CODE REVIEW

**Comment by NiceandGently** [comment]
@monsta 
Can you please test ?
Looks like the issue ocours only with gtk+-3.16.

**Comment by monsta** [comment]
Unfortunately, my only GTK+3 VM has 3.16 too...

**Comment by NiceandGently** [comment]
This is OK, because it fixes the issue for you ;)
@infirit told me yesterday that he don't see the issue with gtk+-3.14.
I quess the reason for this is change with srollbars in scrolled windows.

**Comment by monsta** [comment]
Ah yes, they made these stupid appearing-on-mouse-hover scrollbars. Another shit from gnome devs.
I found out that in Synaptic I can't click on the last list item because once I move the mouse there, a horizontal scrollbar appears over the item... :angry:

**Comment by NiceandGently** [comment]
> I found out that in Synaptic I can't click on the last list item because once I move the mouse there, a horizontal scrollbar appears over the item... :angry:

yes, i saw this too with some apps.
OK, in fedora 21 gtk+-3.14 the issue isn't there,
but using this size request doesn't break the window.

**Pull request closed without merging**
