### PR TITLE
port snippets plugin to gi and libpeas

### PR DESCRIPTION
**Pull request by monsta**
Use ```Tools -> Manage Snippets...``` menu item to open Snippets Manager. You can check the available snippets for various languages there.

How to test it: open some file with code, type one of supported snippets and press Tab.
Example: type ```for``` in C file and you should get this:

snippets-1

Then you can change the values in placeholders to something else. Use Tab and Shift-Tab to move between placeholders.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Without this PR snippets doesn't even show up-we need this to re-enable snippets

**Comment by raveit65** [comment]
hmm, snipset plugin was disabled for 1.17.3 tarball.
......a hint for creating a new tarball wouldn't be helpful.

**Comment by monsta** [comment]
Added a fix for an old visual issue which is present in 1.16 (GTK+2 build) as well, so it will go into backports later. The issue is easily reproducible:

- type ```for```, press Tab

snippets-2

- press Ctrl-Z

snippets-3

After that, you'll have to use Ctrl-Z a few times more to get rid of these remains, and Tab completion might stop working completely until you clean all that and type ```for``` on a new line :slightly_smiling_face:

**Comment by raveit65** [comment]
@monsta 
Can you please rebase against master to have the version bump in this branch?

**Comment by monsta** [comment]
Rebased, should be with 1.17.4 now

**Comment by raveit65** [comment]
Works well, with the full PR is see only one remaining **for** after pressing crtl+z.
I guess this is the expected behaviour?

**Comment by monsta** [comment]
Yes, and then you can press Tab again to get the snippet appear again - previously it didn't always work properly after undo.

**Pull request merged**
