### PR TITLE
externaltools plugin: outputpanel.ui: avoid GtkHBox and GtkVButtonBox

### PR DESCRIPTION
**Pull request by sc0w**
and there is no more deprecations

I don't  know how to show this dialog, the external tools plugin doesn't work here without/with the PR

### CODE REVIEW

**Comment by raveit65** [comment]
The libpeas error i can't reproduce.
After enable the pluging in preferences i have some entries in menu with master.
pluma-external-tools
pluma-external-tools-2
But UI looks different with PR.
pluma-external-tools-3

**Comment by raveit65** [comment]
This fixes the problem for me.
```
--- outputpanel-old.ui	2018-03-05 10:20:26.860729000 +0100
+++ outputpanel.ui	2018-03-05 10:35:16.957386786 +0100
@@ -16,6 +16,7 @@ Version: 2.91.3
       <object class="GtkScrolledWindow" id="scrolledwindow1">
         <property name="visible">True</property>
         <property name="can_focus">False</property>
+        <property name="hexpand">True</property>
         <property name="shadow_type">in</property>
         <child>
           <object class="GtkTextView" id="view">
```

**Comment by sc0w** [comment]
@raveit65 ok, done

**Comment by sc0w** [comment]
merged: https://github.com/mate-desktop/pluma/commit/2b86db36250fd6a9c6add88c4bae3471c8ce47db

**Pull request closed without merging**
