### PR TITLE
remove type & url attr of ulink in translation

### LINKED ISSUE #395: url prefix for Danish help: ghelp -> help (and replacle url location)
https://github.com/mate-desktop/pluma/blob/f64c03771e2f596ad92a9ee62f311c1ec72aebf1/help/da/da.po#L297

https://github.com/mate-desktop/pluma/blob/f64c03771e2f596ad92a9ee62f311c1ec72aebf1/help/da/da.po#L598

### PR DESCRIPTION
**Pull request by rbuj**
Example of generated file:

**help/pluma.pot before:**

msgid "To report a bug or make a suggestion regarding the &lt;application&gt;pluma&lt;/application&gt; application or this manual, follow the directions in the &lt;ulink url=\"help:mate-user-guide/feedback\" type=\"help\"&gt;MATE Feedback Page&lt;/ulink&gt;."
msgstr ""

**help/pluma.pot after:**

msgid "MATE Feedback Page"
msgstr ""

msgid "To report a bug or make a suggestion regarding the <application>pluma</application> application or this manual, follow the directions in the <_:ulink-1/>."
msgstr ""

### CODE REVIEW

**Comment by raveit65** [comment]
Can you please move the link `#395` from commit header to commit body?
In commit header should only be a short description what the commit does.
Links or other comments are belongs to commit body.
This looks better when browsing git history.

And can you cherry-pick commits for help to 1.20 branch after merging?
Plus running ./makepot if nessessary.
Note, before you commit an update for *.pot files you should check if those 2 lines are correct.
```
"Project-Id-Version: MATE Desktop Environment\n"
"Content-Type: text/plain; charset=UTF-8\n"
```
There was a bug in the past with `charset=UTF-8` at transifex-client, which is fixed now, to avoid `distcheck` errors.
For some reason is `Project-Id-Version:` always wrong after generating the resouce file, and it needs to be fixed by
```
sed -i 's/PACKAGE VERSION/MATE Desktop Environment/g' po/*.po
````
or for the help dir.

**Comment by rbuj** [comment]
@raveit65 
I do not advise to call makepot in this PR, as we couldn't perform a cherry-pick to 1.20 branch.

**Comment by raveit65** [comment]
This was only a general advise for user-guide commits.
You know it better than me it we should run ./makepot or picking it to 1.20 branch after merging ;)

**Comment by rbuj** [comment]
@raveit65 
I cherry-picked the commit to 1.20 brand, and I updated pot files for master & 1.20 branches.

**Pull request merged**
